= Node.js Communication with Amazon S3

I'm thinking of simplifying the archive process for notebooks
on Notehsare along the following lines:

. Noteshare prepares the archive on S3, but in a non-public
location.

. Noteshare sends a message to a Node.js server in EC2 asking
it to tar and gzip the archive and at the same time sends
a url to the user where he can download the zipped archive,
along with a message to wait a short time (??).

== Resources

http://www.hacksparrow.com/node-js-amazon-s3-how-to-get-started.html[Getting
started: node & s3] +
https://github.com/Automattic/knox[Knox] + 
http://s3tools.org/usage[S3 Tools - commands] +
http://justinklemm.com/node-js-async-tutorial/[Async tutorial] +



== A start on this project

Below is bare-bones server written in Express that
responds to three simple requests.  Assuming that 
it set up for `localhost:8081`, we proceed as follows:

. Launch the server with `$ node server.js`
. Run `$ curl http://localhost:8081/hello`.  The response is
`I am alive.  Thank you for your concern.`.
. Run `$ curl http://localhost:8081/file/foobar.txt`  The response
is `You asked for file foobar.txt`
. Run `$ curl http://localhost:8081/list`  The response
is a listing of the files in object `manuscript/195` of
bucket `vschool`.




.Server code
[source, javascript]
--
  // File: server.js
  
  var express = require('express');
  var app = express();

  app.get ('/hello', function(req, res) {
    res.end('I am alive. Thank you for your concern.\n')
  });

  app.get("/file/:file_name", function(req, res) {
    res.end("You asked for the file " + req.params.file_name + "\n");
  });

  app.get("/list", function(req, res) {
    listBucket();
    res.end("See console.log for the file list\n");
  });

app.listen(8081);
--


.Code for listBucket()
[source, javascript]
--
function listBucket() {
  var s3 = require('aws2js').load('s3', "HAHA876", "HOHO1234");
  s3.setBucket("vschool");

  var folder = encodeURI('manuscripts/195');
  var url = '?prefix=' + folder;

  s3.get(url, 'xml', function (error, data) {
    n = parseInt((data['Contents']).length)

    console.log(error);

    for (i = 0; i < n; i++) {
      file_name = data['Contents'][i]['Key'];
      console.log((i+1) + ": " + file_name);
    }
    console.log("----------------------");
    console.log(n + " items listed");

  });
}

--

.Example for returned listing
----
{ Name: 'vschool',
  Prefix: 'manuscripts/195',
  Marker: {},
  MaxKeys: '1000',
  IsTruncated: 'false',
  Contents: 
   [ { Key: 'manuscripts/195.ad',
       LastModified: '2015-03-31T00:55:37.000Z',
       ETag: '"87a4be2ab84a292793931ca8f8f190df"',
       Size: '119064',
       Owner: [Object],
       StorageClass: 'STANDARD' },
     { Key: 'manuscripts/195.html',
       LastModified: '2015-03-31T00:55:37.000Z',
       ETag: '"177629a0169bd87ad75d2f5a5c845ee5"',
       Size: '203010',
       Owner: [Object],
       StorageClass: 'STANDARD' }],
  '@': { xmlns: { xmlns: 'http://s3.amazonaws.com/doc/2006-03-01/' } } }
----
