= Node.js Communication with Amazon S3

:numbered:

I'm thinking of simplifying the archive process for notebooks
on Notehsare along the following lines:

. Noteshare prepares the archive on S3, but in a non-public
location.

. Noteshare sends a message to a Node.js server in EC2 asking
it to tar and gzip the archive and at the same time sends
a url to the user where he can download the zipped archive,
along with a message to wait a short time (??).

== Resources

http://www.hacksparrow.com/node-js-amazon-s3-how-to-get-started.html[Getting
started: node & s3] +
https://github.com/Automattic/knox[Knox] + 
http://s3tools.org/usage[S3 Tools - commands] +
http://justinklemm.com/node-js-async-tutorial/[Async tutorial] +



== A start on this project

Below is bare-bones server written in Express that
responds to three simple requests.  Assuming that 
it set up for `localhost:8081`, we proceed as follows:

. Launch the server with `$ node server.js`
. Run `$ curl http://localhost:8081/hello`.  The response is
`I am alive.  Thank you for your concern.`.
. Run `$ curl http://localhost:8081/file/foobar.txt`  The response
is `You asked for file foobar.txt`
. Run `$ curl http://localhost:8081/list-manuscript/199`  The response
is a listing of the files in object `manuscript/199` of
bucket `vschool`.


== Server code

.Server code
[source, javascript]
--
  // File: server.js
  
 var express = require('express');
  var app = express();

  var S3_KEY = 'HOHOH123';
  var S3_SECRET = 'HAHA456';
  var S3_BUCKET = 'vschool';

  app.get ('/hello', function(req, res) {
    res.end('I am alive. Thank you for your concern.\n')
  });

    app.get("/file/:a", function(req, res) {
    file_path = req.params.a
    res.end("You asked for the file " + file_path + "\n");
    get_file(file_path)
  });

  app.get("/file/:a/:b", function(req, res) {
    file_path = req.params.a + "/" + req.params.b
    res.end("You asked for the file " + file_path + "\n");
    get_file(file_path)
  });

  app.get("/file/:a/:b/:c", function(req, res)  {
    file_path = req.params.a + "/" + req.params.b + "/" + req.params.c
    res.end("You asked for the file " + file_path + "\n");
    get_file(file_path)
  });

 app.get("/list-manuscript/:ms_number", function(req, res) {
    listArchive(req.params.ms_number);
    res.end("See console.log for the file list\n");
  });

app.listen(8081);
--

=== listArchive(ms_number)

.Code for listArchive(ms_number)
[source, javascript]
--
function listArchive(ms_number) {

  var s3 = require('aws2js').load('s3', S3_KEY, S3_SECRET);
  s3.setBucket("vschool");

  var folder = encodeURI('manuscripts/'+ms_number);
  var url = '?prefix=' + folder;


  s3.get(url, 'xml', function (error, data) {
    n = parseInt((data['Contents']).length)

    console.log(error);

    var file_list = [ ];

    for (i = 0; i < n; i++) {
      file_name = data['Contents'][i]['Key'];
      file_list.push(file_name);
    }

    for (i in file_list) {
      console.log((parseInt(i)+1) + ': '+ file_list[i]);
    }
    console.log("----------------------");
    console.log(file_list.length + " items listed");

    async = require('async')
    async.map(file_list, identity, function(err, results){
        // results is now an array of stats for each file
        console.log(results);
    });


  });


}
--

=== get_file(path)

.Code
[source, javascript]
--
var get_file = function(path) {

    var source_path = 'manuscripts/' + path
    // var dest_path = 'ladidah.txt'
    var dest_path =  'manuscript/' + dest_name(path)
    console.log("downloaded: " + source_path + ' as ' + dest_path);

    var knox = require('knox').createClient({
      key: S3_KEY,
      secret: S3_SECRET,
      bucket: S3_BUCKET
    });

    // We need the fs module so that we can write the stream to a file
    var fs = require('fs');
    // Set the file name for WriteStream
    var file = fs.createWriteStream(dest_path);
    knox.getFile(source_path, function(err, res) {
      res.on('data', function(data) { file.write(data); });
      res.on('end', function(chunk) { file.end(); });
    });

  }
--

=== dest_name(source_name)

[source, javascript]
--
  var dest_name = function(source_name) {

    var part = source_name.split('/')
    if (part.length == 1) {
      return part[0]
    } else if (part.length == 2) {
      return part[1]
    } else if (part.length == 3) {
      return part[1] + "/" + part[2]
    } else if (part.length == 4) {
      return part[2] + '/' + part[3]
    } else {
      return 'oops'
    }
  }
--


== S3 Listing

.Example for returned listing
----
{ Name: 'vschool',
  Prefix: 'manuscripts/195',
  Marker: {},
  MaxKeys: '1000',
  IsTruncated: 'false',
  Contents: 
   [ { Key: 'manuscripts/195.ad',
       LastModified: '2015-03-31T00:55:37.000Z',
       ETag: '"87a4be2ab84a292793931ca8f8f190df"',
       Size: '119064',
       Owner: [Object],
       StorageClass: 'STANDARD' },
     { Key: 'manuscripts/195.html',
       LastModified: '2015-03-31T00:55:37.000Z',
       ETag: '"177629a0169bd87ad75d2f5a5c845ee5"',
       Size: '203010',
       Owner: [Object],
       StorageClass: 'STANDARD' }],
  '@': { xmlns: { xmlns: 'http://s3.amazonaws.com/doc/2006-03-01/' } } }
----
